[package]
name = "rust-htip"
version = "0.1.0"
authors = ["marios <haha@myzen.jaist.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macaddr = "1.0"
lazy_static = "1.4.0"
pcap = "0.7"
